PUNCH_DAMAGE = 25
KICK_DAMAGE = 40
PUNCH_SEQUENCE_MAX_DELAY = 0 * 60 # to be determined

JUMP_COOLDOWN = 0 * 60 # to be determined

OVERHEAD_DAMAGE = 50

TRACER_DAMAGE = 30
TRACER_MAX_CHARGES = 5
TRACER_CHARGE_TIME = 2.5 * 60
TRACER_COOLDOWN_TIME = 0.5 * 60
TRACER_ACTIVE_TIME = 4 * 60
TRACER_PROC_DAMAGE = 45

SWING_MAX_CHARGES = 3
SWING_CHARGE_TIME = 6 * 60
WHIFF_REWARD_TIME = 0 * 60 # to be determined

GOH_DAMAGE = 25
GOHT_DAMAGE = 50
GOH_MAX_CHARGES = 1
GOH_CHARGE_TIME = 8 * 60

UPPERCUT_DAMAGE = 55
UPPERCUT_MAX_CHARGES = 2
UPPERCUT_CHARGE_TIME = 6 * 60
UPPERCUT_COOLDOWN_TIME = 2 * 60

SYMBIOTE_DAMAGE = 50
SYMBIOTE_MAX_CHARGES = 1
SYMBIOTE_CHARGE_TIME = 40 * 60